# 1.指定当前目录下需要编进程序去的文件
obj-y += led.o
obj-y += keyboard.o
obj-y += ds18b20.o
obj-y += dh11.o
obj-y += irda.o
obj-y += sr501.o
obj-y += sr04.o
obj-y += motor.o

obj-y += dac.o
obj-y += oled.o
obj-y += adxl345.o

obj-y += eeprom.o
obj-y += rtc.o